version: '3.8'

services:
  # database:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: studentsystem
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  backend:
    build: ./studentsystem
    container_name: studentsystem_backend
    restart: always
    ports:
      - "8080:8080"
    # depends_on:
    #   - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cv1bpftds78s73dmomk0-a.frankfurt-postgres.render.com:5432/geraete
      SPRING_DATASOURCE_USERNAME: m347
      SPRING_DATASOURCE_PASSWORD: TsFHAbD0H0O8NUbVqTik7q5CnQhVTCAe
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./studentfrontend
    container_name: studentfrontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  chat:
    build: ./chat
    container_name: chat_backend
    restart: always
    ports:
      - "8081:8081"

# volumes:
#   mysql_data:
