name: CI/CD Pipeline

on:
  push:
    branches:
      - ci-cd
      - main
      - postgresDB

permissions:
  contents: read
  packages: write

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        working-directory: ./studentfrontend
        run: npm ci
      - name: Lint Frontend
        working-directory: ./studentfrontend
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21 for Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Backend with Maven (Skip Tests)
        run: |
          cd studentsystem || exit 1
          mvn clean package -DskipTests || exit 1
      - name: Build Chat with Maven (Skip Tests)
        run: |
          cd chat || exit 1
          mvn clean package -DskipTests || exit 1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./studentsystem
          push: true
          tags: ghcr.io/ctygamer/studentensystem/backend-image:latest
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./studentfrontend
          push: true
          tags: ghcr.io/ctygamer/studentensystem/frontend-image:latest
      - name: Build and push Chat Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./chat
          push: true
          tags: ghcr.io/ctygamer/studentensystem/chat-image:latest

  integration-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 for Tests
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Integrationstests für Backend-Service (studentsystem)
      - name: Run Integration Tests for Backend Service (studentsystem)
        run: |
          cd studentsystem || exit 1 
          mvn verify -Dtest=*IT -Dsurefire.failIfNoSpecifiedTests=false || exit 1

      # Testergebnisse hochladen und veröffentlichen (nur wenn vorhanden)
      - name: Upload Test Results for Backend Service
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results-backend
          path: studentsystem/target/surefire-reports/**/*.xml

      - name: Publish Test Results for Backend Service
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2.5.0
        with:
          files: studentsystem/target/surefire-reports/**/*.xml
